=== nchauhan5/ElasticSearchPOC/Development/Code/endeca/assembler/assembler-integration/search-api/src/main/resources/SearchAPISchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="PACKAGES">
		<xs:annotation>
			<xs:documentation>Root Node Packages Containing a List of Packages with all the relevant information</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PACKAGE" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Node PACKAGE. Child nodes within this contains all package information returned by search api</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="OFFERINFO" minOccurs="1" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>Offer Info Containing Offer Related Data </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="date" type="xs:date" use="required"/>
									<xs:attribute name="stay" type="xs:int" use="required"/>
									<xs:attribute name="priceTotal" type="xs:decimal" use="required"/>
									<xs:attribute name="pricePerPerson" type="xs:decimal"/>
									<xs:attribute name="deposit" type="xs:decimal"/>
									<xs:attribute name="coachTransfer" type="xs:boolean"/>
									<xs:attribute name="carHire" type="xs:boolean"/>
									<xs:attribute name="worldCare" type="xs:boolean"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="HOTELINFO" minOccurs="1" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>Hotel Info containing information about the Hotel that is returned within the package</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="brand" type="xs:string"/>
									<xs:attribute name="id" type="xs:string" use="required"/>
									<xs:attribute name="commercialPriority" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="ROOMINFO" minOccurs="1" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Rooms Info containing information about the rooms that are within the hotel</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PARTYINFO" minOccurs="1" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="adults" type="xs:int"/>
												<xs:attribute name="children" type="xs:int"/>
												<xs:attribute name="infant" type="xs:int"/>
												<xs:attribute name="seniors" type="xs:int"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="roomTypeName" type="xs:string"/>
									<xs:attribute name="roomCode" type="xs:string" use="required"/>
									<xs:attribute name="availability" type="xs:boolean" use="required"/>
									<xs:attribute name="priceTotal" type="xs:decimal" use="required"/>
									<xs:attribute name="pricePerPerson" type="xs:decimal"/>
									<xs:attribute name="discountTotal" type="xs:decimal"/>
									<xs:attribute name="discountPerPerson" type="xs:decimal"/>
									<xs:attribute name="defaultBoard" type="xs:string"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="BOARDINFO" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Information about the Board information</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="boardCode" type="xs:string" use="required"/>
									<xs:attribute name="boardPrice" type="xs:decimal" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="FLIGHTINFO" minOccurs="2" maxOccurs="2">
								<xs:annotation>
									<xs:documentation>Information about the In-bound and Out-bound flight  details</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="departurePort" type="xs:string" use="required"/>
									<xs:attribute name="departureDate" type="xs:date" use="required"/>
									<xs:attribute name="departureTime" type="xs:string" use="required"/>
									<xs:attribute name="arrivalPort" type="xs:string" use="required"/>
									<xs:attribute name="arrivalDate" type="xs:date" use="required"/>
									<xs:attribute name="arrivalTime" type="xs:string" use="required"/>
									<xs:attribute name="availability" type="xs:int" use="required"/>
									<xs:attribute name="flightNo" type="xs:string" use="required"/>
									<xs:attribute name="airplaneCode" type="xs:string" use="required"/>
									<xs:attribute name="dreamliner" type="xs:boolean"/>
									<xs:attribute name="car" type="xs:boolean"/>
									<xs:attribute name="meals" type="xs:boolean"/>
									<xs:attribute name="routeOptionCode" type="xs:string"/>
									<xs:attribute name="routeOptionAvailability" type="xs:string"/>
									<xs:attribute name="pricePerAdult" type="xs:string"/>
									<xs:attribute name="pricePerChildren" type="xs:string"/>
									<xs:attribute name="flightType" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="DURATIONDATESINFO">
								<xs:annotation>
									<xs:documentation>Durations and Calendar Response Info</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="AVAILABLEDURATIONS" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="durations" type="xs:int" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="CALENDARINFO" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="date" type="xs:date" use="required"/>
												<xs:attribute name="availability" type="xs:boolean" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="RATINGREVIEWSINFO" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Information about various rating and reviews information</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="rating" type="xs:decimal"/>
									<xs:attribute name="reviews" type="xs:string"/>
									<xs:attribute name="percentage" type="xs:decimal"/>
									<xs:attribute name="category" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="FACETINFO" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="FACET" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="code" type="xs:string" use="required"/>
									<xs:attribute name="name" type="xs:string" use="optional"/>
									<xs:attribute name="count" type="xs:int" use="required"/>
									<xs:attribute name="min" type="xs:float" use="optional"/>
									<xs:attribute name="max" type="xs:float" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="categoryCode" type="xs:string" use="required"/>
						<xs:attribute name="categoryName" type="xs:string" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="packagesCount" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nchauhan5/ElasticSearchPOC/Development/Code/endeca/assembler/assembler-integration/elastic-webapp/src/main/resources/searchapiresponse/searchapiresponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2014 rel. 2 sp1 (x64) (http://www.altova.com) -->
<PACKAGES xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" packagesCount="String" xsi:noNamespaceSchemaLocation="SearchAPISchema.xsd">
	<PACKAGE>
		<OFFERINFO date="2014-10-27" stay="5" priceTotal="1202.00" pricePerPerson="601.00" deposit="601.00" coachTransfer="true"
			carHire="true" worldCare="true" />
		<HOTELINFO brand="F" id="2843" commercialPriority="251" />
		<ROOMINFO roomTypeName="DoubleBedRoom" roomCode="AQ013" availability="true" priceTotal="1202.00" pricePerPerson="601.00"
			discountTotal="601.00" discountPerPerson="140.00" defaultBoard="AI">
			<PARTYINFO adults="2" children="0" infant="0" seniors="0" />
		</ROOMINFO>
		<ROOMINFO roomTypeName="SingleBedRoom" roomCode="AQ014" availability="true" priceTotal="601.00" pricePerPerson="300.00"
			discountTotal="300.00" discountPerPerson="140.00" defaultBoard="AI">
			<PARTYINFO adults="2" children="0" infant="0" seniors="0" />
		</ROOMINFO>
		<BOARDINFO boardCode="BB" boardPrice="1500.00" />
		<FLIGHTINFO departurePort="GLA" departureDate="2014-10-27" departureTime="0720" arrivalPort="LPA" arrivalDate="2014-10-30"
			arrivalTime="1200" availability="25" flightNo="TOM1100" airplaneCode="String" dreamliner="true" car="true" meals="true"
			routeOptionCode="String" routeOptionAvailability="String" pricePerAdult="String" pricePerChildren="String" flightType="OUTBOUND" />

		<FLIGHTINFO departurePort="LPA" departureDate="2014-10-30" departureTime="2130" arrivalPort="GLA" arrivalDate="2014-10-30"
			arrivalTime="0210" availability="35" flightNo="TOM1601" airplaneCode="String" dreamliner="true" car="true" meals="true"
			routeOptionCode="String" routeOptionAvailability="String" pricePerAdult="String" pricePerChildren="String" flightType="INBOUND" />
		<DURATIONDATESINFO>
			<AVAILABLEDURATIONS durations="7" />
			<CALENDARINFO date="2014-10-30" availability="true" />
		</DURATIONDATESINFO>
		<RATINGREVIEWSINFO rating="5" reviews="String" percentage="0" category="String" />
	</PACKAGE>
	<FACETINFO categoryCode="AF0001">
		<FACET code="AF0001" count="88" min="3.0" max="5.0" />
	</FACETINFO>
	<FACETINFO categoryCode="FT000F">
		<FACET code="LST1" count="2" />
		<FACET code="ST3" count="7" />
		<FACET code="STF11" count="2" />
		<FACET code="STF7" count="2" />
		<FACET code="STF3" count="1" />
		<FACET code="STF9" count="1" />
	</FACETINFO>
	<FACETINFO categoryCode="FT000H">
		<FACET code="ST14" count="5" />
		<FACET code="ST4" count="2" />
		<FACET code="ST37" count="1" />
		<FACET code="LST28" count="2" />
	</FACETINFO>
	<FACETINFO categoryCode="FT000P">
		<FACET code="ST23" count="5" />
		<FACET code="STP8" count="8" />
	</FACETINFO>
	<FACETINFO categoryCode="FT000S">
		<FACET code="ST11" count="1" />
		<FACET code="ST25" count="1" />
		<FACET code="ST42" count="7" />
		<FACET code="ST29" count="6" />
		<FACET code="STS3" count="5" />
		<FACET code="ST35" count="2" />
	</FACETINFO>
	<FACETINFO categoryCode="AF0002">
		<FACET code="P00057" count="3" />
		<FACET code="P00053" count="1" />
		<FACET code="Beach" count="1" />
		<FACET code="P00052" count="2" />
		<FACET code="P00050" count="2" />
		<FACET code="P00056" count="1" />
		<FACET code="P00060" count="1" />
	</FACETINFO>
	<FACETINFO categoryCode="FT000O">
		<FACET code="ST20" count="6" />
		<FACET code="STO2" count="2" />
		<FACET code="STO7" count="1" />
	</FACETINFO>
	<FACETINFO categoryCode="FT000E">
		<FACET code="ST8" count="7" />
		<FACET code="LST51" count="2" />
		<FACET code="ST22" count="7" />
		<FACET code="ST7" count="1" />
	</FACETINFO>
</PACKAGES>
